<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::statement('ALTER TABLE leftovers ALTER COLUMN local_id DROP DEFAULT');

        DB::statement("
            ALTER TABLE leftovers
            ALTER COLUMN local_id
            ADD GENERATED BY DEFAULT AS IDENTITY
            (INCREMENT BY 1 START WITH 1 MINVALUE 1)
        ");

        DB::statement("
            DO $$
            DECLARE n bigint;
            BEGIN
              SELECT COALESCE(MAX(local_id) + 1, 1) INTO n FROM leftovers;
              EXECUTE format('ALTER TABLE leftovers ALTER COLUMN local_id RESTART WITH %s', n);
            END$$;
        ");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::statement('ALTER TABLE leftovers ALTER COLUMN local_id DROP IDENTITY IF EXISTS');
        DB::statement('ALTER TABLE leftovers ALTER COLUMN local_id DROP DEFAULT');
    }
};
