<?php

return [
    'doctype_dictionaries' => [
        'adr',
        'cell_type',
        'cell_status',
        'company_status',
        'country',
        'download_zone',
        'measurement_unit',
        'package_type',
        'position',
        'settlement',
        'street',
        'storage_type',
        'transport_brand',
        'transport_download',
        'transport_kind',
        'transport_type',
        'company',
        'warehouse',
        'transport',
        'additional_equipment',
        'user',
        'document_order',
        'document_goods_invoice',
        'currencies',
        'cargo_type',
        'delivery_type',
        'basis_for_ttn',
        'all_cells',
    ],
];
